version: '2'

services:
  server:
    image: landoop/fast-data-dev
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9092:9092"
      - "9581-9584:9581-9584"
    environment:
      - RUNTESTS=0
      - ADV_HOST=localhost
